# Generated by Django 3.2.9 on 2021-12-05 11:28

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='appointment',
            fields=[
                ('deid', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(default='', max_length=100)),
                ('mail', models.CharField(max_length=100)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('make_an_appointment', models.CharField(max_length=100)),
                ('message', models.CharField(max_length=800)),
            ],
        ),
    ]
