# Generated by Django 3.2.9 on 2021-12-05 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='sub_e_mail',
            fields=[
                ('e_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=255)),
            ],
        ),
    ]
