# Generated by Django 3.2.9 on 2021-12-07 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0003_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact1',
            fields=[
                ('deid', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=100)),
                ('Email', models.CharField(max_length=200)),
                ('subject', models.CharField(max_length=900)),
                ('message', models.CharField(max_length=800)),
            ],
        ),
    ]
